"""podcast model audio_file field

Revision ID: e6c97f588891
Revises: f0c28c729069
Create Date: 2020-11-24 21:33:34.090442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c97f588891'
down_revision = 'f0c28c729069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('audio_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'audio_file')
    # ### end Alembic commands ###
